name: github-actions-cheerful

on: 
  push:
    branches: [deploy_sojeong, deploy_mikyung, deploy_jongbo]

jobs:
  print-test:
    runs-on: ubuntu-latest
    env:
          DOCKER_USERNAME: ${{ 
            github_ref_name == 'deploy_sojeong' && secrets.DOCKER_USERNAME_SOJEONG ||
            github_ref_name == 'deploy_mikyung' && secrets.DOCKER_USERNAME_MIKYUNG ||
            github_ref_name == 'deploy_jongbo' && secrets.DOCKER_USERNAME_JONGBO
            }}
          DOCKER_PASSWORD: ${{ 
            github_ref_name == 'deploy_sojeong' && secrets.DOCKER_PASSWORD_SOJEONG ||
            github_ref_name == 'deploy_mikyung' && secrets.DOCKER_PASSWORD_MIKYUNG ||
            github_ref_name == 'deploy_jongbo' && secrets.DOCKER_PASSWORD_JONGBO
            }}
    steps: 
      - name: checkout
        uses: actions/checkout@v5.0.0
        with:
          ref: ${{ github.ref }}

      - name: docker login
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: install JDK 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: build spring boot app
        run: |
          cd backend
          echo ${{ env.APPLICATION_SECRET }} | base64 --decode > ./src/main/resources/application-secret.yml
          chmod 777 ./mvnw
          ./mvnw clean package -DskipTests
          docker build -t ${{ env.DOCKER_USERNAME }}/spring-app:latest .
          docker push ${{ env.DOCKER_USERNAME }}/spring-app:latest

      - name: build react app
        run: |
          cd web
          echo ${{ env.REACT_ENV }} | base64 --decode > ./.env
          npm install
          npm run build
          docker build -t ${{ env.DOCKER_USERNAME }}/react-app:latest .
          docker push ${{ env.DOCKER_USERNAME }}/react-app:latest

         
